


=== Console agent 4.1.0

This release of the Console agent includes security improvements, bug fixes, and the following features:

The 4.1.0 release is available for standard mode and restricted mode.


.Renamed Agent status indicators
Renamed the status indicators for the Console agent from *Active* and *Inactive* to *Connected* and *Disconnected* to make their purpose more clear.

.Support for Redhat Enterprise Linux (RHEL) 9.6 and Podman 5.4.0
The Console agent now supports RHEL 9.6 and Podman 5.4.0. In addition, when using RHEL 9 and higher, NetApp supports podman-compose 1.5.0.



=== NetApp Console administration
This release includes the following:


.New email address for NetApp Console notifications
The email address that sends NetApp Console notifications has changed to *service@console.netapp.com* from *service@console.bluexp.netapp.com*. NetApp recommends updating any email rules to the allow *service@console.netapp.com* to ensure you continue to receive NetApp Console email notifications.