=== Introducing the well-architected dashboard in NetApp Console

The well-architected dashboard in NetApp Console provides a single view of your storage systems and configurations across accounts and regions. The dashboard provides insights and recommendations to help you achieve operational excellence. You can view the well-architected status of your configurations, configuration issues organized by the pillars of the well-architected framework for the storage type you use, and a list of configuration issues and recommendations.

Learn more about the link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html[well-architected dashboard].

The well-architected dashboard in the Console is available for the following storage systems:

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html[Amazon FSx for NetApp ONTAP]
* link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html[Cloud Volumes ONTAP in Microsoft Azure]

=== Build your own custom rules

Write custom rules in plain language to make sure your systems follow your organization's standards and NetApp best practices. Test the rules with a dry run, then schedule them to run across your environments.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html[Learn more about custom rules]