//All links and images must use the absolute URL.


=== Console agent 4.3.0

The 4.3.0 release supports both standard mode and restricted mode.

This release of the Console agent includes security improvements, bug fixes, and the following features:


.Ability to validate network connections of Console agents
You can now validate network connections of connected Console agents directly from the NetApp Console. This feature helps verify connectivity and troubleshoot issues with Console agents. 

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access[Learn how to run configuration checks on Console agents.]

.Additional Google Cloud permissions for Cloud Volumes ONTAP
To support Cloud Volumes ONTAP management in Google Cloud, the Console agent now requires an additional permission. The following permission has been added to the service account used by the Console agent: compute.forwardingRules.update

link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log[View the permissions change log.]




=== NetApp Console administration
This release includes the following:


.Support for federation when NetApp Console is in restricted mode
You can now enable federation for a NetApp Console organization that is in restricted mode. This allows users to log in to the Console using their corporate credentials while maintaining the security benefits of restricted mode.

.Read-only mode 
You can set a NetApp Console organization to read-only mode. In read-only mode, users can view resources and settings but cannot make any changes. An Org admin or Super admin can enable read-only mode for an organization. When read-only mode is enabled, users with administrative roles must manually elevate their permissions to make changes as needed.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html[Learn how to enable read-only mode for a Console organization.]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings[Learn how to elevate your role when your organization is in read-only mode.]



